# Implementar el docker-compose.yaml
version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: boston-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BOSTON
    volumes:
      - boston-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"
  app:
    image: tux550/app:v1.0
    container_name: boston-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db

volumes:
  boston-data: